"""Revised-spec drafter — S1 stub.

S1 is the contract surface. The drafter accepts an Epic + Execution and
returns a RevisedSpec keyed by ``epic.external_id`` against a small
hand-crafted lookup. J4 replaces this dispatch with a real LLM call.

Returning canned outputs (rather than mechanically synthesizing one from
the inputs) is intentional: it forces downstream callers to handle the
fact that the drafter can *re-write* criteria — drop, merge, rephrase —
and not merely echo them.

EPIC-001..005 are hand-written; EPIC-006..030 are templated entries
generated by ``_templated_epic_builder`` (S3). Templated entries still
emit non-empty RevisedSpec values that satisfy ``validate_revised_spec``
when paired with the matching Execution generated by
``scripts/gen_drafter_fixtures.py``.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING

from receipts.drafter.models import Citation, Epic, Execution, RevisedSpec

if TYPE_CHECKING:
    from receipts.judge.l2 import LLMJudge


def _draft_epic_001(_execution: Execution) -> RevisedSpec:
    """EPIC-001 — batch endpoint was dropped mid-sprint."""
    criterion = "GET /v1/spec returns the latest revised spec for a given epic_id."
    return RevisedSpec(
        acceptance_criteria=[criterion],
        citations={
            criterion: [
                Citation(artifact_kind="pr", external_id="PR-101", locator=None),
                Citation(artifact_kind="pr", external_id="PR-102", locator=None),
                Citation(artifact_kind="meeting", external_id="MTG-21", locator="1"),
                Citation(artifact_kind="thread", external_id="THR-7", locator=None),
            ],
        },
        drift_summary=(
            "Batch lookup criterion was dropped in MTG-21 to keep v1 scope to "
            "single-epic GET. Endpoint shipped via PR-101/PR-102."
        ),
    )


def _draft_epic_002(_execution: Execution) -> RevisedSpec:
    """EPIC-002 — shipped as scoped, no drift."""
    criterion = "Appending an event extends the SHA-256 chain."
    return RevisedSpec(
        acceptance_criteria=[criterion],
        citations={
            criterion: [
                Citation(artifact_kind="pr", external_id="PR-201", locator=None),
                Citation(artifact_kind="meeting", external_id="MTG-30", locator="0"),
            ],
        },
        drift_summary="Shipped as scoped — no drift.",
    )


def _draft_epic_003(_execution: Execution) -> RevisedSpec:
    """EPIC-003 — judge L0 patterns, one criterion split into two."""
    cri_a = "L0 scorer flags missing-citation patterns in <50ms per criterion."
    cri_b = "L0 scorer emits a structured failure-class label per finding."
    return RevisedSpec(
        acceptance_criteria=[cri_a, cri_b],
        citations={
            cri_a: [Citation(artifact_kind="pr", external_id="PR-301")],
            cri_b: [
                Citation(artifact_kind="pr", external_id="PR-302"),
                Citation(artifact_kind="thread", external_id="THR-12"),
            ],
        },
        drift_summary=(
            "Original single criterion split into latency + label criteria "
            "after THR-12 surfaced ambiguity in 'flags' wording."
        ),
    )


def _draft_epic_004(_execution: Execution) -> RevisedSpec:
    """EPIC-004 — connector shim, criterion rephrased."""
    criterion = "Linear connector replays a fixture issue and round-trips fields."
    return RevisedSpec(
        acceptance_criteria=[criterion],
        citations={
            criterion: [
                Citation(artifact_kind="pr", external_id="PR-401"),
                Citation(artifact_kind="meeting", external_id="MTG-44", locator="2"),
            ],
        },
        drift_summary=(
            "Criterion rephrased from 'reads issues' to explicit fixture-replay "
            "+ round-trip per MTG-44 decision #2."
        ),
    )


def _draft_epic_005(_execution: Execution) -> RevisedSpec:
    """EPIC-005 — meeting transcript ingest, scope expanded."""
    cri_a = "Transcript ingest writes a meeting row with decision array."
    cri_b = "Transcript ingest deduplicates by transcript external_id."
    return RevisedSpec(
        acceptance_criteria=[cri_a, cri_b],
        citations={
            cri_a: [Citation(artifact_kind="pr", external_id="PR-501")],
            cri_b: [
                Citation(artifact_kind="pr", external_id="PR-502"),
                Citation(artifact_kind="meeting", external_id="MTG-55", locator="0"),
            ],
        },
        drift_summary=(
            "Dedup criterion added after MTG-55 reviewed accidental double-writes "
            "in the synthetic week fixture."
        ),
    )


_STUB_REGISTRY: dict[str, Callable[[Execution], RevisedSpec]] = {
    "EPIC-001": _draft_epic_001,
    "EPIC-002": _draft_epic_002,
    "EPIC-003": _draft_epic_003,
    "EPIC-004": _draft_epic_004,
    "EPIC-005": _draft_epic_005,
}


# ---------------------------------------------------------------------------
# Templated stubs (EPIC-006..030)
# ---------------------------------------------------------------------------
#
# Each templated entry shares the same shape:
#   - two acceptance criteria (one feature, one observability/safety)
#   - citations point at PR-{NNN}01 / PR-{NNN}02 / MTG-{NNN} / THR-{NNN}
#     where NNN is the zero-padded epic number; the generator wires the
#     matching Execution so the validator accepts the round-trip.
#   - drift_summary alternates "no drift" and "criterion rephrased" by parity
#     so the corpus contains both signal classes.
#
# Subjects/areas come from a small word bank so the criteria read plausibly
# even though they're generated from a template.

_EPIC_SUBJECTS = (
    ("billing", "invoice export"),
    ("auth", "step-up verification"),
    ("search", "query rerank"),
    ("onboarding", "welcome flow"),
    ("dashboard", "live tile refresh"),
    ("webhooks", "delivery retry"),
    ("reporting", "scheduled digest"),
    ("audit", "actor attribution"),
    ("settings", "tenant scope"),
    ("notifications", "batched delivery"),
    ("integrations", "Slack connector"),
    ("integrations", "Linear connector"),
    ("exports", "CSV streaming"),
    ("imports", "duplicate detection"),
    ("roles", "viewer downgrade"),
    ("permissions", "deny-by-default"),
    ("calendar", "ICS feed"),
    ("tasks", "bulk reassign"),
    ("pricing", "annual toggle"),
    ("invoices", "PDF rendering"),
    ("sandbox", "fresh-tenant reset"),
    ("telemetry", "p95 dashboard"),
    ("alerts", "noisy-neighbor mute"),
    ("compliance", "SOC2 audit hook"),
    ("retention", "delete-after-90d job"),
)
assert len(_EPIC_SUBJECTS) == 25  # EPIC-006..030


def _epic_template_index(external_id: str) -> int:
    """Return the 0-based template index for EPIC-006..030."""
    if not external_id.startswith("EPIC-") or len(external_id) != 8:
        raise KeyError(external_id)
    n = int(external_id[5:])
    if n < 6 or n > 30:
        raise KeyError(external_id)
    return n - 6


def _templated_epic_builder(external_id: str) -> Callable[[Execution], RevisedSpec]:
    """Construct a builder for a templated EPIC-NNN entry (6 <= NNN <= 30)."""
    idx = _epic_template_index(external_id)
    area, feature = _EPIC_SUBJECTS[idx]
    nnn = int(external_id[5:])
    pr_a = f"PR-{nnn:03d}01"
    pr_b = f"PR-{nnn:03d}02"
    mtg = f"MTG-{nnn:03d}"
    thr = f"THR-{nnn:03d}"
    # Alternate drift class by parity so the corpus has both signal types.
    rephrased = nnn % 2 == 0

    cri_a = f"{area.capitalize()} {feature} ships with feature-flag kill-switch documented."
    cri_b = f"{area.capitalize()} {feature} emits success + error telemetry per call."

    citations = {
        cri_a: [
            Citation(artifact_kind="pr", external_id=pr_a),
            Citation(artifact_kind="meeting", external_id=mtg, locator="0"),
        ],
        cri_b: [
            Citation(artifact_kind="pr", external_id=pr_b),
            Citation(artifact_kind="thread", external_id=thr),
        ],
    }
    if rephrased:
        drift_summary = (
            f"{external_id}: criterion (b) rephrased from generic 'instrumented' "
            f"to explicit 'success + error telemetry per call' after {thr}."
        )
    else:
        drift_summary = f"{external_id}: shipped as scoped — no drift."

    def _builder(_execution: Execution) -> RevisedSpec:
        return RevisedSpec(
            acceptance_criteria=[cri_a, cri_b],
            citations=citations,
            drift_summary=drift_summary,
        )

    _builder.__doc__ = f"{external_id} — templated stub ({area}/{feature})."
    _builder.__name__ = f"_draft_epic_{nnn:03d}"
    return _builder


for _n in range(6, 31):
    _ext = f"EPIC-{_n:03d}"
    _STUB_REGISTRY[_ext] = _templated_epic_builder(_ext)
del _n, _ext


def draft_revised_spec(
    epic: Epic,
    execution: Execution,
    *,
    judge: LLMJudge | None = None,
) -> RevisedSpec:
    """Return a RevisedSpec for ``epic`` against ``execution``.

    Dispatch order (deliberate, do not swap):

    1. **Stub registry** — ``EPIC-001..030`` always return canned values
       so substrate fixtures stay byte-stable. The ``judge`` kwarg is
       ignored for these epics.
    2. **LLM path** — for epics outside the registry, if a ``judge`` is
       provided we route through :func:`draft_revised_spec_llm`. The
       judge handles record/replay + Merkle attestation.
    3. **Unimplemented** — no stub + no judge raises
       ``NotImplementedError``, matching the pre-P1-5 behaviour so
       callers that never opted in see no change.
    """
    builder = _STUB_REGISTRY.get(epic.external_id)
    if builder is not None:
        return builder(execution)

    if judge is not None:
        # Imported lazily to keep the substrate import graph minimal:
        # ``llm_path`` pulls in ``receipts.judge.l2`` which transitively
        # depends on the Merkle log. Substrate consumers that never use
        # the LLM path should not pay that import cost.
        from receipts.drafter.llm_path import draft_revised_spec_llm

        return draft_revised_spec_llm(epic, execution, judge)

    raise NotImplementedError(
        f"S1 stub has no canned RevisedSpec for epic external_id={epic.external_id!r}; "
        "pass `judge=LLMJudge(...)` to dispatch via the real-LLM path (P1-5)."
    )
